# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pdf2text_pb2 as clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2


class Pdf2TextStub(object):
    """## API Overview

    Pdf2Text is a service used to convert PDF documents to text.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
            '/clouway.api.pdf2text.v1.Pdf2Text/Convert',
            request_serializer=clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertRequest.SerializeToString,
            response_deserializer=clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertResponse.FromString,
        )


class Pdf2TextServicer(object):
    """## API Overview

    Pdf2Text is a service used to convert PDF documents to text.
    """

    def Convert(self, request, context):
        """Convert converts passed PDF payload into text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Pdf2TextServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Convert': grpc.unary_unary_rpc_method_handler(
            servicer.Convert,
            request_deserializer=clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertRequest.FromString,
            response_serializer=clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'clouway.api.pdf2text.v1.Pdf2Text', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Pdf2Text(object):
    """## API Overview

    Pdf2Text is a service used to convert PDF documents to text.
    """

    @staticmethod
    def Convert(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clouway.api.pdf2text.v1.Pdf2Text/Convert',
                                             clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertRequest.SerializeToString,
                                             clouway_dot_pdf2text_dot_v1_dot_pdf2text__pb2.ConvertResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
