# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clouway/pdf2text/v1/pdf2text.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"clouway/pdf2text/v1/pdf2text.proto\x12\x17\x63louway.api.pdf2text.v1\"!\n\x0e\x43onvertRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x1f\n\x0f\x43onvertResponse\x12\x0c\n\x04text\x18\x02 \x01(\t2j\n\x08Pdf2Text\x12^\n\x07\x43onvert\x12\'.clouway.api.pdf2text.v1.ConvertRequest\x1a(.clouway.api.pdf2text.v1.ConvertResponse\"\x00\x42\x66\n\x1d\x63om.clouway.cloud.pdf2text.v1B\rPdf2TextProtoP\x01Z4clouway.golang.org/genproto/api/pdf2text/v1;pdf2textb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clouway.pdf2text.v1.pdf2text_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.clouway.cloud.pdf2text.v1B\rPdf2TextProtoP\001Z4clouway.golang.org/genproto/api/pdf2text/v1;pdf2text'
  _CONVERTREQUEST._serialized_start=63
  _CONVERTREQUEST._serialized_end=96
  _CONVERTRESPONSE._serialized_start=98
  _CONVERTRESPONSE._serialized_end=129
  _PDF2TEXT._serialized_start=131
  _PDF2TEXT._serialized_end=237
# @@protoc_insertion_point(module_scope)
